type User @entity {
  id: ID!
  address: String!
  createdAt: BigInt!
}

type Asset @entity {
  id: ID!
  token: String!
  factory: String!
  createdAt: BigInt!
  method: Int!
}

type Proposal @entity {
  id: ID!
  proposalId: BigInt!
  proposer: String!
  description: String
  startBlock: BigInt!
  endBlock: BigInt!
  executed: Boolean!
  createdAt: BigInt!
  governor: String!
  targets: [String!]!
  values: [BigInt!]!
  calldatas: [String!]!
}

type Deposit @entity {
  id: ID!
  caller: String!
  owner: String!
  vault: String!
  assets: BigInt!
  shares: BigInt!
  createdAt: BigInt!
  transaction: String!
}
