name: Blockchain_Project_CI
on: [push, pull_request]

jobs:
  test-and-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install Solc 0.8.24
        run: forge solc install 0.8.24
      - name: Run Tests
        run: forge test -vvv
      - name: Slither Static Analysis
        uses: crytic/slither-action@v0.3.0
        continue-on-error: true
        with:
          target: "."
          slither-args: "--config-file slither.config.json"
